//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABESSPEntities : DbContext
    {
        public ABESSPEntities()
            : base("name=ABESSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailyAttendance> DailyAttendances { get; set; }
        public virtual DbSet<DailyAttendanceEdit> DailyAttendanceEdits { get; set; }
        public virtual DbSet<DailyAttendanceEmailLog> DailyAttendanceEmailLogs { get; set; }
        public virtual DbSet<DailyOvertime> DailyOvertimes { get; set; }
        public virtual DbSet<DaysName> DaysNames { get; set; }
        public virtual DbSet<DeviceDataError> DeviceDataErrors { get; set; }
        public virtual DbSet<DeviceEmpRemove> DeviceEmpRemoves { get; set; }
        public virtual DbSet<DownloadTime> DownloadTimes { get; set; }
        public virtual DbSet<EmpFace> EmpFaces { get; set; }
        public virtual DbSet<EmpFP> EmpFPs { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<JobCardApp> JobCardApps { get; set; }
        public virtual DbSet<JobCardAppFlow> JobCardAppFlows { get; set; }
        public virtual DbSet<JobCardDetail> JobCardDetails { get; set; }
        public virtual DbSet<JobCardStage> JobCardStages { get; set; }
        public virtual DbSet<JobCardType> JobCardTypes { get; set; }
        public virtual DbSet<LeaveApplication> LeaveApplications { get; set; }
        public virtual DbSet<LeaveApplicationFlow> LeaveApplicationFlows { get; set; }
        public virtual DbSet<LeaveCarryForward> LeaveCarryForwards { get; set; }
        public virtual DbSet<LeaveCPLBalance> LeaveCPLBalances { get; set; }
        public virtual DbSet<LeaveCPLEmpBalance> LeaveCPLEmpBalances { get; set; }
        public virtual DbSet<LeaveCPLPool> LeaveCPLPools { get; set; }
        public virtual DbSet<LeaveData> LeaveDatas { get; set; }
        public virtual DbSet<LeavePolicy> LeavePolicies { get; set; }
        public virtual DbSet<LeaveQuotaPeriod> LeaveQuotaPeriods { get; set; }
        public virtual DbSet<LeaveQuotaYear> LeaveQuotaYears { get; set; }
        public virtual DbSet<LeaveStage> LeaveStages { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<MonthData> MonthDatas { get; set; }
        public virtual DbSet<MonthDataEdit> MonthDataEdits { get; set; }
        public virtual DbSet<MonthlyERP> MonthlyERPs { get; set; }
        public virtual DbSet<MonthlyERPLWOP> MonthlyERPLWOPs { get; set; }
        public virtual DbSet<MonthOTStage> MonthOTStages { get; set; }
        public virtual DbSet<OTApprovedHistory> OTApprovedHistories { get; set; }
        public virtual DbSet<OTPolicy> OTPolicies { get; set; }
        public virtual DbSet<ProcessDate> ProcessDates { get; set; }
        public virtual DbSet<ProcessRequest> ProcessRequests { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<ReaderDutyCode> ReaderDutyCodes { get; set; }
        public virtual DbSet<ReaderType> ReaderTypes { get; set; }
        public virtual DbSet<Remark> Remarks { get; set; }
        public virtual DbSet<RosterApplication> RosterApplications { get; set; }
        public virtual DbSet<RosterDetail> RosterDetails { get; set; }
        public virtual DbSet<RosterType> RosterTypes { get; set; }
        public virtual DbSet<ServiceLog> ServiceLogs { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<ShiftChanged> ShiftChangeds { get; set; }
        public virtual DbSet<ShiftChangedEmp> ShiftChangedEmps { get; set; }
        public virtual DbSet<ACCUUP> ACCUUPs { get; set; }
        public virtual DbSet<FPTemplate> FPTemplates { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<EmpDailyRoster> EmpDailyRosters { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<AppUserAccessType> AppUserAccessTypes { get; set; }
        public virtual DbSet<AppUserDepartment> AppUserDepartments { get; set; }
        public virtual DbSet<AppUserLocation> AppUserLocations { get; set; }
        public virtual DbSet<AppUserRole> AppUserRoles { get; set; }
        public virtual DbSet<AppUserTM> AppUserTMS { get; set; }
        public virtual DbSet<AuditForm> AuditForms { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<AuditLogChild> AuditLogChilds { get; set; }
        public virtual DbSet<AuditLogDetail> AuditLogDetails { get; set; }
        public virtual DbSet<AuditLogParent> AuditLogParents { get; set; }
        public virtual DbSet<AuditType> AuditTypes { get; set; }
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Crew> Crews { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeCrewChange> EmployeeCrewChanges { get; set; }
        public virtual DbSet<EmployeeGender> EmployeeGenders { get; set; }
        public virtual DbSet<EmployeeImage> EmployeeImages { get; set; }
        public virtual DbSet<EmployeeLog> EmployeeLogs { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<JTCommon> JTCommons { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationCommon> LocationCommons { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationEmail> NotificationEmails { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<OrganizationalUnit> OrganizationalUnits { get; set; }
        public virtual DbSet<OUCommon> OUCommons { get; set; }
        public virtual DbSet<SMTPDetail> SMTPDetails { get; set; }
        public virtual DbSet<FinalSettelmentFlow> FinalSettelmentFlows { get; set; }
        public virtual DbSet<FinalSettelmentStatu> FinalSettelmentStatus { get; set; }
        public virtual DbSet<FinalSettlement> FinalSettlements { get; set; }
        public virtual DbSet<FinancialYear> FinancialYears { get; set; }
        public virtual DbSet<PayrollPeriod> PayrollPeriods { get; set; }
        public virtual DbSet<DeviceData> DeviceDatas { get; set; }
        public virtual DbSet<VAT_CPLBalance> VAT_CPLBalance { get; set; }
        public virtual DbSet<VAT_DailyAttedanceEdit> VAT_DailyAttedanceEdit { get; set; }
        public virtual DbSet<VAT_DailyAttendance> VAT_DailyAttendance { get; set; }
        public virtual DbSet<VAT_DailyAttendanceDetail> VAT_DailyAttendanceDetail { get; set; }
        public virtual DbSet<VAT_DailyOvertime> VAT_DailyOvertime { get; set; }
        public virtual DbSet<VAT_DeviceData> VAT_DeviceData { get; set; }
        public virtual DbSet<VAT_JobCardApplication> VAT_JobCardApplication { get; set; }
        public virtual DbSet<VAT_JobCardFlow> VAT_JobCardFlow { get; set; }
        public virtual DbSet<VAT_LeaveApplication> VAT_LeaveApplication { get; set; }
        public virtual DbSet<VAT_LeaveApplicationFlow> VAT_LeaveApplicationFlow { get; set; }
        public virtual DbSet<VAT_LeaveCPLEmpBalance> VAT_LeaveCPLEmpBalance { get; set; }
        public virtual DbSet<VAT_LeaveData> VAT_LeaveData { get; set; }
        public virtual DbSet<VAT_LeaveQuotaYearly> VAT_LeaveQuotaYearly { get; set; }
        public virtual DbSet<VAT_MonthData> VAT_MonthData { get; set; }
        public virtual DbSet<VAT_MonthDataEdit> VAT_MonthDataEdit { get; set; }
        public virtual DbSet<VAT_MonthlyERP> VAT_MonthlyERP { get; set; }
        public virtual DbSet<VAT_MonthlyERPLWOP> VAT_MonthlyERPLWOP { get; set; }
        public virtual DbSet<VAT_MonthlySheet> VAT_MonthlySheet { get; set; }
        public virtual DbSet<VAT_MonthlySummary> VAT_MonthlySummary { get; set; }
        public virtual DbSet<VAT_OvertimeHistory> VAT_OvertimeHistory { get; set; }
        public virtual DbSet<VAT_Reader> VAT_Reader { get; set; }
        public virtual DbSet<VAT_RosterApplication> VAT_RosterApplication { get; set; }
        public virtual DbSet<VAT_RosterDetail> VAT_RosterDetail { get; set; }
        public virtual DbSet<VAT_ServiceLog> VAT_ServiceLog { get; set; }
        public virtual DbSet<VAT_Shift> VAT_Shift { get; set; }
        public virtual DbSet<VAT_ShiftChanged> VAT_ShiftChanged { get; set; }
        public virtual DbSet<VEP_JobCardApplication> VEP_JobCardApplication { get; set; }
        public virtual DbSet<VHR_AppUser> VHR_AppUser { get; set; }
        public virtual DbSet<VHR_CommonLocation> VHR_CommonLocation { get; set; }
        public virtual DbSet<VHR_Crew> VHR_Crew { get; set; }
        public virtual DbSet<VHR_Designation> VHR_Designation { get; set; }
        public virtual DbSet<VHR_EmployeeCrewChange> VHR_EmployeeCrewChange { get; set; }
        public virtual DbSet<VHR_EmployeeProfile> VHR_EmployeeProfile { get; set; }
        public virtual DbSet<VHR_EmploymentType> VHR_EmploymentType { get; set; }
        public virtual DbSet<VHR_Grade> VHR_Grade { get; set; }
        public virtual DbSet<VHR_JobTitle> VHR_JobTitle { get; set; }
        public virtual DbSet<VHR_Location> VHR_Location { get; set; }
        public virtual DbSet<VHR_OrganizationalUnit> VHR_OrganizationalUnit { get; set; }
        public virtual DbSet<VHR_User> VHR_User { get; set; }
        public virtual DbSet<VHR_UserCommonLocation> VHR_UserCommonLocation { get; set; }
        public virtual DbSet<VHR_UserEmployee> VHR_UserEmployee { get; set; }
    }
}
