//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int PUserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<System.DateTime> LastActiveDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> UserAccessTypeID { get; set; }
        public string UserRoleID { get; set; }
        public Nullable<bool> HasESSP { get; set; }
    
        public virtual AppUserAccessType AppUserAccessType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
