//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogDetail
    {
        public int PID { get; set; }
        public string TableName { get; set; }
        public string TableValues { get; set; }
        public string TableValues1 { get; set; }
        public Nullable<int> ChangedUserID { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public string Operation { get; set; }
        public Nullable<int> ChangeRecordEmployeeID { get; set; }
    }
}
