//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceData
    {
        public long PDeviceDataID { get; set; }
        public int EmpID { get; set; }
        public string EmpDate { get; set; }
        public Nullable<int> FpID { get; set; }
        public string CardNo { get; set; }
        public System.DateTime EntDate { get; set; }
        public System.DateTime EntTime { get; set; }
        public short ReaderID { get; set; }
        public Nullable<byte> ReaderDutyID { get; set; }
        public Nullable<bool> Process { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> ModeOfEntry { get; set; }
        public Nullable<int> OID { get; set; }
    }
}
