//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDailyRoster
    {
        public int PEmpDailyRosterID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string OEmpID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> ShiftMin { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
