//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFP
    {
        public int PEmpFPID { get; set; }
        public string EmpFP1 { get; set; }
        public string EmpFP2 { get; set; }
        public string EmpFP3 { get; set; }
        public string EmpFP4 { get; set; }
        public Nullable<int> FPID { get; set; }
        public string EmpFP5 { get; set; }
    }
}
