//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFace
    {
        public int PEmpFaceID { get; set; }
        public string EmpFace1 { get; set; }
        public string EmpFace2 { get; set; }
        public string EmpFace3 { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
