//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLog
    {
        public int PID { get; set; }
        public Nullable<System.DateTime> CDateTime { get; set; }
        public int PEmployeeID { get; set; }
        public string OEmpID { get; set; }
        public Nullable<int> FPID { get; set; }
        public string EmployeeName { get; set; }
        public string TelephoneNo { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string CNIC { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> DesigationID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> OUID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CrewID { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<bool> FaceTemp { get; set; }
        public Nullable<bool> FPTemp { get; set; }
        public Nullable<bool> ProcessAttendance { get; set; }
        public Nullable<short> OTPolicyID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ALPolicyID { get; set; }
        public Nullable<int> CLPolicyID { get; set; }
        public Nullable<int> SLPolicyID { get; set; }
        public Nullable<int> CPLPolicyID { get; set; }
    }
}
