//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialYear()
        {
            this.PayrollPeriods = new HashSet<PayrollPeriod>();
        }
    
        public int PFinancialYearID { get; set; }
        public string FYName { get; set; }
        public Nullable<System.DateTime> FYStartDate { get; set; }
        public Nullable<System.DateTime> FYEndDate { get; set; }
        public Nullable<bool> FYStatus { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPeriod> PayrollPeriods { get; set; }
    }
}
