//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPTemplate
    {
        public int ID { get; set; }
        public string FP1 { get; set; }
        public string FP2 { get; set; }
        public string FP3 { get; set; }
    }
}
