//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCardApp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobCardApp()
        {
            this.JobCardDetails = new HashSet<JobCardDetail>();
        }
    
        public int PJobCardAppID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateStarted { get; set; }
        public System.DateTime DateEnded { get; set; }
        public int JobCardTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public Nullable<short> Minutes { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> OtherValue { get; set; }
        public string JobCardStageID { get; set; }
        public string SystemRemarks { get; set; }
    
        public virtual JobCardStage JobCardStage { get; set; }
        public virtual JobCardType JobCardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCardDetail> JobCardDetails { get; set; }
    }
}
