//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveType()
        {
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveDatas = new HashSet<LeaveData>();
            this.LeavePolicies = new HashSet<LeavePolicy>();
        }
    
        public byte PLeaveTypeID { get; set; }
        public string LeaveTypeName { get; set; }
        public string ReportName { get; set; }
        public Nullable<bool> HalfLeave { get; set; }
        public string HLRptName { get; set; }
        public Nullable<bool> HalfAbsent { get; set; }
        public string HLAbsentRptName { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> HasPolicy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveData> LeaveDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavePolicy> LeavePolicies { get; set; }
    }
}
