//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavePolicy
    {
        public short PLeavePolicyID { get; set; }
        public string LeavePolicyName { get; set; }
        public byte LeaveTypeID { get; set; }
        public Nullable<bool> UpdateBalance { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> ProRata { get; set; }
        public Nullable<bool> CF { get; set; }
        public Nullable<byte> CFMinDaysDed { get; set; }
        public Nullable<byte> CFMaxDaysDed { get; set; }
        public Nullable<byte> CFPenalityDays { get; set; }
        public Nullable<short> CFMaxDays { get; set; }
        public Nullable<bool> WithOutPay { get; set; }
        public Nullable<bool> WithHalfPay { get; set; }
        public Nullable<bool> WithFullPay { get; set; }
        public Nullable<bool> Encashable { get; set; }
        public Nullable<bool> ActiveAfterJoinDate { get; set; }
        public Nullable<bool> ActiveAfterProbation { get; set; }
        public Nullable<bool> ActiveAfterCustomDays { get; set; }
        public Nullable<short> CustomDays { get; set; }
        public Nullable<short> TotalDays { get; set; }
        public Nullable<bool> CountRestDays { get; set; }
        public Nullable<bool> CountGZDays { get; set; }
        public Nullable<bool> DeductRestDays { get; set; }
        public Nullable<bool> DeductGZDays { get; set; }
        public Nullable<double> AttachmentForDays { get; set; }
        public Nullable<double> MinimumDays { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
    }
}
