//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCarryForward
    {
        public int PLeaveCarryForwardID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<double> RemainingLeaves { get; set; }
        public Nullable<double> CollapseLeaves { get; set; }
        public Nullable<double> CarryForwardLeaves { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
