//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCPLEmpBalance
    {
        public int PLeaveCPLEmpBalanceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> IsExpire { get; set; }
        public Nullable<double> RemainingDays { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public Nullable<double> Used { get; set; }
    }
}
