//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveQuotaYear
    {
        public int PLeaveQuotaYearID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<byte> LeaveTypeID { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> GrandRemaining { get; set; }
        public Nullable<double> YearlyTotal { get; set; }
        public Nullable<double> YearlyRemaining { get; set; }
        public Nullable<double> CFFromLastYear { get; set; }
        public Nullable<double> CFRemaining { get; set; }
    }
}
