//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveQuotaPeriod
    {
        public int PLeaveQuotaPeriodID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> PayrollPeriodID { get; set; }
        public Nullable<byte> LeaveTypeID { get; set; }
        public Nullable<double> StartNoOfDays { get; set; }
        public Nullable<double> ConsumedDays { get; set; }
        public Nullable<double> RemainingDays { get; set; }
    }
}
