//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveData
    {
        public string PLeaveDataEmpDate { get; set; }
        public Nullable<int> LeaveAppID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime AttDate { get; set; }
        public byte LeaveTypeID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<bool> HalfLeave { get; set; }
        public Nullable<bool> FirstHalf { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsAccum { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
