//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollPeriod()
        {
            this.MonthDatas = new HashSet<MonthData>();
        }
    
        public int PPayrollPeriodID { get; set; }
        public string PRName { get; set; }
        public Nullable<System.DateTime> PRStartDate { get; set; }
        public Nullable<System.DateTime> PREndDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<int> TotalEmps { get; set; }
        public string PeriodStageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthData> MonthDatas { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
    }
}
