//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessRequest
    {
        public int PAttProcesserSchedulerID { get; set; }
        public string PeriodTag { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public short LocationID { get; set; }
        public short CatID { get; set; }
        public Nullable<bool> ProcessingDone { get; set; }
        public string Criteria { get; set; }
        public Nullable<bool> ProcessCat { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpNo { get; set; }
        public Nullable<bool> SystemGenerated { get; set; }
        public string Remarks { get; set; }
    }
}
