//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark
    {
        public byte PRemarkID { get; set; }
        public string RemarksName { get; set; }
        public string RemarkValue { get; set; }
        public Nullable<bool> Enable { get; set; }
    }
}
