//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterType
    {
        public byte PRosterTypeID { get; set; }
        public string RosterTypeName { get; set; }
        public Nullable<bool> Repeat { get; set; }
    }
}
