//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftChangedEmp
    {
        public int PEmpShiftChangeID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Shift Shift { get; set; }
    }
}
