//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftChanged
    {
        public int PShiftChangedID { get; set; }
        public string ChangedShiftDesc { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public short ShiftID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public byte DayOff1 { get; set; }
        public byte DayOff2 { get; set; }
        public short MonMin { get; set; }
        public short TueMin { get; set; }
        public short WedMin { get; set; }
        public short ThuMin { get; set; }
        public short FriMin { get; set; }
        public short SatMin { get; set; }
        public short SunMin { get; set; }
        public short MinHrs { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<short> LateIn { get; set; }
        public Nullable<short> EarlyIn { get; set; }
        public Nullable<short> EarlyOut { get; set; }
        public Nullable<short> LateOut { get; set; }
        public Nullable<short> OverTimeMin { get; set; }
        public Nullable<bool> HasBreak { get; set; }
        public Nullable<short> BreakMin { get; set; }
        public Nullable<short> HalfDayBreakMin { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual Shift Shift { get; set; }
    }
}
