//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_LeaveApplication
    {
        public int EmpID { get; set; }
        public int PLeaveAppID { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public byte LeaveTypeID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public float NoOfDays { get; set; }
        public Nullable<bool> IsHalf { get; set; }
        public Nullable<bool> FirstHalf { get; set; }
        public Nullable<bool> HalfAbsent { get; set; }
        public string LeaveReason { get; set; }
        public string LeaveAddress { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string LeaveStageID { get; set; }
        public int LineManagerID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RejectRemarks { get; set; }
        public Nullable<bool> IsDeducted { get; set; }
        public Nullable<bool> TimeOffice { get; set; }
        public string LeaveTypeName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> FPID { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> DesigationID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> OUID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public string LocationName { get; set; }
        public string EmploymentTypeName { get; set; }
        public string GradeName { get; set; }
        public string JobTitleName { get; set; }
        public string DesignationName { get; set; }
        public string OTPolicyName { get; set; }
        public string ShiftName { get; set; }
        public string OEmpID { get; set; }
        public string CrewName { get; set; }
        public Nullable<int> CrewID { get; set; }
        public Nullable<int> PUserID { get; set; }
        public Nullable<double> CalenderDays { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public string LMEmployeeName { get; set; }
        public Nullable<bool> IsAccum { get; set; }
        public string PathName { get; set; }
        public string Status { get; set; }
        public Nullable<int> SubmittedByUserID { get; set; }
        public Nullable<int> OUCommonID { get; set; }
        public string OUCommonName { get; set; }
        public string OUName { get; set; }
    }
}
