//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_Reader
    {
        public string ReaderTypeName { get; set; }
        public string ReaderType { get; set; }
        public string LocationName { get; set; }
        public bool ClearRecords { get; set; }
        public Nullable<int> LocID { get; set; }
        public bool Status { get; set; }
        public byte RdrTypeID { get; set; }
        public short IpPort { get; set; }
        public string IpAdd { get; set; }
        public byte ReaderDutyCodeID { get; set; }
        public string ReaderName { get; set; }
        public short PReaderID { get; set; }
        public string ReaderDutyName { get; set; }
    }
}
