//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_MonthDataEdit
    {
        public int PMonthDataEditID { get; set; }
        public Nullable<int> PayrollPeriodID { get; set; }
        public Nullable<System.DateTime> DataEditDate { get; set; }
        public Nullable<double> OldTotalDays { get; set; }
        public Nullable<double> OldPaidDays { get; set; }
        public Nullable<double> OldAbsentDays { get; set; }
        public Nullable<double> NewTotalDays { get; set; }
        public Nullable<double> NewPaidDays { get; set; }
        public Nullable<double> NewAbsentDays { get; set; }
        public string NewRemarks { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EmployeeName { get; set; }
        public string OUName { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DesignationName { get; set; }
        public string JobTitleName { get; set; }
        public int PUserID { get; set; }
        public string UserName { get; set; }
        public string PRName { get; set; }
        public string UserEmployeeName { get; set; }
        public Nullable<int> UserLocationID { get; set; }
        public string UserLocationName { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> DesigationID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> OUID { get; set; }
        public string EmploymentTypeName { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CommonLocationID { get; set; }
        public string CommonLocationName { get; set; }
        public string JTCommonName { get; set; }
        public Nullable<int> JTCommonID { get; set; }
        public string OJobTitleID { get; set; }
        public Nullable<int> OUCommonID { get; set; }
        public string OUCommonName { get; set; }
        public string OOUID { get; set; }
        public string OEmpID { get; set; }
        public string OLocationID { get; set; }
        public string ODesignationID { get; set; }
        public string OEmployeementTypeID { get; set; }
        public string OGradeID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public Nullable<int> CrewID { get; set; }
        public string CrewName { get; set; }
    }
}
