//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_LeaveQuotaYearly
    {
        public string FYName { get; set; }
        public Nullable<System.DateTime> FYStartDate { get; set; }
        public Nullable<System.DateTime> FYEndDate { get; set; }
        public Nullable<bool> FYStatus { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<byte> LeaveTypeID { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> GrandRemaining { get; set; }
        public Nullable<double> YearlyTotal { get; set; }
        public Nullable<double> YearlyRemaining { get; set; }
        public Nullable<double> CFFromLastYear { get; set; }
        public string LeaveTypeName { get; set; }
        public int PLeaveQuotaYearID { get; set; }
        public string EmployeeName { get; set; }
        public string JobTitleName { get; set; }
        public string OUName { get; set; }
        public string OEmpID { get; set; }
        public string DesignationName { get; set; }
        public string LocationName { get; set; }
        public string EmploymentTypeName { get; set; }
        public Nullable<double> CFRemaining { get; set; }
    }
}
