//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_JobCardApplication
    {
        public string JobCardName { get; set; }
        public string DutyCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int PJobCardAppID { get; set; }
        public System.DateTime DateStarted { get; set; }
        public System.DateTime DateEnded { get; set; }
        public int JobCardTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<short> JobCardAppWorkMin { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> OtherValue { get; set; }
        public string JobCardStageID { get; set; }
        public string JobCardStageName { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public Nullable<short> Minutes { get; set; }
        public Nullable<int> FPID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string JobTitleName { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public string OEmpID { get; set; }
        public Nullable<int> PEmployeeID { get; set; }
        public string DesignationName { get; set; }
    }
}
