//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_CPLBalance
    {
        public int PLeaveCPLEmpBalanceID { get; set; }
        public Nullable<double> Used { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public Nullable<double> RemainingDays { get; set; }
        public Nullable<bool> IsExpire { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string LocationName { get; set; }
        public string EmploymentTypeName { get; set; }
        public string GradeName { get; set; }
        public string DesignationName { get; set; }
        public string OTPolicyName { get; set; }
        public string ShiftName { get; set; }
        public string CrewName { get; set; }
        public string SLPolicyName { get; set; }
        public string CLPolicyName { get; set; }
        public string CompanyName { get; set; }
        public string OUName { get; set; }
        public string CPLPolicyName { get; set; }
        public string OUCommonName { get; set; }
        public string JTCommonName { get; set; }
        public string LMUserName { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string OEmpID { get; set; }
        public Nullable<int> DesigationID { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<short> OTPolicyID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public Nullable<int> OUID { get; set; }
        public Nullable<int> ALPolicyID { get; set; }
        public Nullable<int> CrewID { get; set; }
        public Nullable<int> CLPolicyID { get; set; }
        public Nullable<int> SLPolicyID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CPLPolicyID { get; set; }
        public Nullable<int> OUCommonID { get; set; }
        public string JobTitleName { get; set; }
        public Nullable<int> JTCommonID { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public Nullable<int> CommonLocationID { get; set; }
        public string CommonLocationName { get; set; }
        public string ALPolicyName { get; set; }
    }
}
