//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_OvertimeHistory
    {
        public int POTApprovedOTHistoryID { get; set; }
        public Nullable<int> MonthDataID { get; set; }
        public Nullable<int> SubmittedToID { get; set; }
        public Nullable<short> OldSingleOT { get; set; }
        public Nullable<short> NewCPLConverted { get; set; }
        public Nullable<short> OldCPLConverted { get; set; }
        public Nullable<short> OldDoubleOT { get; set; }
        public Nullable<short> NewDoubleOT { get; set; }
        public Nullable<short> NewSingleOT { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string OTStageID { get; set; }
        public Nullable<int> SubmittedByID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string PRName { get; set; }
        public string EmployeeName { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> DesigationID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> OUID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public string LocationName { get; set; }
        public string EmploymentTypeName { get; set; }
        public string GradeName { get; set; }
        public string ShiftName { get; set; }
        public string OEmpID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string CrewName { get; set; }
        public Nullable<int> CrewID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string OUCommonName { get; set; }
        public Nullable<int> OUCommonID { get; set; }
        public string JobTitleName { get; set; }
        public string OJobTitleID { get; set; }
        public Nullable<int> JTCommonID { get; set; }
        public string JTCommonName { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public string FYName { get; set; }
        public string UserEmployeeName { get; set; }
        public string OUName { get; set; }
        public Nullable<int> PayrollPeriodID { get; set; }
    }
}
