//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_MonthlyERPLWOP
    {
        public int PMonthlyERPLWOPID { get; set; }
        public string OEmpID { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<bool> IsHalf { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string EmployeeName { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> PayrollPeriodID { get; set; }
    }
}
