//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHR_OrganizationalUnit
    {
        public int POUID { get; set; }
        public string OUName { get; set; }
        public string OOUID { get; set; }
        public bool Status { get; set; }
        public string OUCommonName { get; set; }
        public Nullable<int> OUCommonID { get; set; }
    }
}
