//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHR_UserEmployee
    {
        public Nullable<int> UserEmpID { get; set; }
        public string UserName { get; set; }
        public int PUserID { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<System.DateTime> UserLastActiveDate { get; set; }
        public Nullable<int> UserAccessTypeID { get; set; }
        public string UserRoleID { get; set; }
        public string UserEmployeeName { get; set; }
        public Nullable<int> UserFPID { get; set; }
        public Nullable<int> UserJobTitleID { get; set; }
        public Nullable<int> UserLocationID { get; set; }
        public string UserJobTitleName { get; set; }
        public string UserLocationName { get; set; }
        public Nullable<bool> HasESSP { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public string LMUserName { get; set; }
        public string LMEmployeeName { get; set; }
        public Nullable<int> LMEmployeeID { get; set; }
        public string OEmpID { get; set; }
        public string OfficialEmailID { get; set; }
        public string CommonLocationName { get; set; }
        public Nullable<int> CommonLocationID { get; set; }
        public string OUName { get; set; }
        public Nullable<int> OUID { get; set; }
        public string Password { get; set; }
        public string DesignationName { get; set; }
        public Nullable<int> JTCommonID { get; set; }
        public string Status { get; set; }
    }
}
