//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHR_Crew
    {
        public string LocationName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public bool Status { get; set; }
        public string CrewName { get; set; }
        public int PCrewID { get; set; }
    }
}
