//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHR_Designation
    {
        public int PDesignationID { get; set; }
        public string DesignationName { get; set; }
        public string ODesignationID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string JobTitleName { get; set; }
        public Nullable<int> JobTitleID { get; set; }
    }
}
